services:
  server:
    container_name: void-server
    image: jus1d/void-server:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      - CONFIG_PATH=./config/dev.yaml
    ports:
      - "6969:6969"
