services:
  api:
    container_name: void-api
    image: ghcr.io/voidcontests/api:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      CONFIG_PATH: ./config/dev.yaml
    ports:
      - "6969:6969"
    networks:
      - voidcontests

networks:
  voidcontests:
    name: voidcontests
    external: true
