env: "local" # local, dev or prod

http:
    address: ":6969"
    timeout: 4s
    idle_timeout: 60s

security:
    signature_key: "some secret key"
    salt: "salt for hashing"

postgres:
    host: "localhost"
    port: "1337"
    user: "postgres"
    name: "postgres"
    password: "unhackable password"
    sslmode: "disable"
